### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by jackoliver** [criipto/verify-with-reactjs#1]
`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:121:11)
    at Object.join (path.js:1039:7)
    at noopServiceWorkerMiddleware (/Users/XXX/Code/verify-with-reactjs/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/index.js:317:13)
    at /Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/Users/XXX/Code/verify-with-reactjs/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/index.js:317:13)
    at /Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/Users/XXX/Code/verify-with-reactjs/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/Users/XXX/Code/verify-with-reactjs/node_modules/express/lib/router/layer.js:95:5)`

Getting this error after `npm start`. Installed all the dependencies no problem, but it won't run.

/J

**Comment by goranlisak** [comment]
Hello @jackoliver,

thank you for showing interest in this. Could you pleas try running `npm install react-scripts @latest` to update the 'react-scripts' package to the latest version?

Pleas let us know if it works for you, so we can commit the changes.

Thank you!

**Comment by jackoliver** [comment]
Yeah, I actually planned to submit a PR with a newer version of react scripts. Works a charm. 

:)

**Comment by goranlisak** [comment]
Thank you for the feedback!
